CHORES = {
    'set_table':    {'Sunday': 'Eliza',
                     'Monday': 'Henry',
                     'Tuesday': 'Noah',
                     'Wednesday': 'Isaac',
                     'Thursday': 'Noah',
                     'Friday': 'Henry',
                     'Saturday': 'Noah'},
    'dishes':       {'Sunday': 'Isaac',
                     'Monday': 'Eliza',
                     'Tuesday': 'Levi',
                     'Wednesday': 'Rebecca',
                     'Thursday': 'Eliza',
                     'Friday': 'Noah',
                     'Saturday': 'Isaac'},
    'garbage':      {'Sunday': 'Levi',
                     'Monday': 'Noah',
                     'Tuesday': 'Eliza',
                     'Wednesday': 'Noah',
                     'Thursday': 'Isaac',
                     'Friday': 'Isaac',
                     'Saturday': 'Eliza'},
    'walk_dog':     {'Sunday': 'Levi',
                     'Monday': 'Isaac',
                     'Tuesday': 'Noah',
                     'Wednesday': 'Eliza',
                     'Thursday': 'Isaac',
                     'Friday': 'Noah',
                     'Saturday': 'Eliza'},
    'scoop_poop':   {'Sunday': 'Levi',
                     'Monday': 'Henry',
                     'Tuesday': 'Noah',
                     'Wednesday': 'Eliza',
                     'Thursday': 'Noah',
                     'Friday': 'Henry',
                     'Saturday': 'Isaac'},
    'feed_dog':     {'Sunday': 'Eliza',
                     'Monday': 'Isaac',
                     'Tuesday': 'Henry',
                     'Wednesday': 'Isaac',
                     'Thursday': 'Noah',
                     'Friday': 'Eliza',
                     'Saturday': 'Noah'},
}
